### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by maris205** [ipfs-force-community/filscan-backend#5]
go build, then:
go: github.com/ipfs-force-community/gosf@v0.1.16: parsing go.mod:
        module declares its path as: gitlab.forceup.in/dev-go/gosf
                but was required as: github.com/ipfs-force-community/gosf

**Comment by dayu26** [comment]
fixed, try again pls.

**Comment by MindFy** [comment]
go: github.com/ipfs-force-community/gosf@v0.1.16: parsing go.mod:
        module declares its path as: gitlab.forceup.in/dev-go/gosf
                but was required as: github.com/ipfs-force-community/gosf

**Comment by dayu26** [comment]
we will look into this

**Comment by coder-van** [comment]
go: github.com/ipfs-force-community/gosf@v0.1.16: parsing go.mod:
        module declares its path as: gitlab.forceup.in/dev-go/gosf
                but was required as: github.com/ipfs-force-community/gosf

me too

**Comment by sedasdas** [comment]
same

**Comment by hznuksco** [comment]
go: github.com/ipfs-force-community/gosf@v0.1.16: parsing go.mod:
	module declares its path as: gitlab.forceup.in/dev-go/gosf
	        but was required as: github.com/ipfs-force-community/gosf

Are you sure you've solved the problem?

**Comment by wo4zhuzi** [comment]
I have the same problem

**Comment by hznuksco** [comment]
Ok, I've spent a day trying to troubleshoot this.
First the go.mod needs to be changed

github.com/ipfs-force-community/common v0.1 .1
github.com/ipfs-force-community/gosf v0.1 .1. 16

Download gosf and replace all the gitlab paths in it with github 
then 
replace github.com/ipfs-force-community/ gosf => ... /gosf

Finally you need to modify the lotus project go.mod 

github.com/ipfs/go-filestore v0.0.2  Replace github.com/ipfs/go-filestore v1.0.0

**Comment by dayu26** [comment]
> ok, I've spent a day trying to troubleshoot this.
> 
> First the go.mod needs to be changed
> 
> github.com/ipfs-force-community/common v0.1 .1
> github.com/ipfs-force-community/gosf v0.1 .1. 16
> 
> Download gosf and replace all the gitlab paths in it with github
> 
> then
> 
> replace github.com/ipfs-force-community/ gosf => ... /gosf
> 
> Finally lotus needs to be changed to v0.2.7 and you need to modify the lotus project go.mod
> 
> github.com/ipfs/go-filestore v0.0.2 Replace github.com/ipfs/go-filestore v1.0.0
> 
> but! api are all v0.2.7 api, which is the same as the latest lotus The api is not the same (e.g. different fields returned, etc.), so it requires magic to change a lot of code in this project. keke

THX a lot! it works!
