### ISSUE TITLE
从API获取的出块奖励和浏览器上不一致

### ISSUE THREAD

**Issue by wytangpei** [ipfs-force-community/filscan-backend#6]
请问下为何在浏览器上显示的区块奖励和从API获取的奖励不一致呢？
能否解释下差异？
应以哪个值为准？
![image](https://user-images.githubusercontent.com/40230489/83368628-22392080-a3ec-11ea-95ae-5639d096b0d7.png)
![image](https://user-images.githubusercontent.com/40230489/83368741-7fcd6d00-a3ec-11ea-88b9-89c068d4faa0.png)

**Comment by wytangpei** [comment]
sorry 图传错了
![image](https://user-images.githubusercontent.com/40230489/83368710-64626200-a3ec-11ea-9859-61ffc02b8638.png)

**Comment by wuzhanfly** [comment]
What lotus version are you using? I can't sync

**Comment by dayu26** [comment]
It is update!
